### ISSUE TITLE
element-ui无法配置表单填充规则

### ISSUE THREAD

**Issue by cooper1x** [gkl2013/form-help#1]
https://element.eleme.cn/#/zh-CN/component/form#dong-tai-zeng-jian-biao-dan-xiang
![image](https://user-images.githubusercontent.com/9080789/164913489-d3c0baa2-67e4-4c73-a578-3699360adc2d.png)
![image](https://user-images.githubusercontent.com/9080789/164913496-e3ba070d-a9f5-4efb-aced-8874697ea095.png)
点了没有反应。

**Comment by gkl2013** [comment]
等页面完全加载完成后生效

**Comment by bestK** [comment]
![image](https://user-images.githubusercontent.com/14979305/203675812-ee38c86b-a826-474e-8363-58e34da45ae6.png)
这种后台管理界面的也无法生成规则
